#+TITLE:     React - The Complete Guide
#+AUTHOR:    Martim Lima
#+EMAIL:     (concat "martim.d.lima" at-sign "protonmail.com")
#+DATE:      10-10-2020
#+LANGUAGE:  en
#+OPTIONS:   H:4 num:nil toc:2
#+PROPERTY: header-args :dir ~/Documents/org/temp
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

-----

* Introduction
 :PROPERTIES:
  :CATEGORY: Introduction
  :END:

** What is React?

"A javascript Library for building User Interfaces"

A browser side javascript framework - no need for server side rendering

user Interfaces - Components - enable flexibility and reusibility by constructing small modular pieces of code

** Why React?
    :PROPERTIES:
    :CATEGORY: Introduction
    :END:

+ UI State becomes difficult to handle with Vanilla Javascript
+ Focus on Business Logic, not on preventing your App from exploding
+ Huge Ecosystem, Active Community, High Performance

** Single Page Applications / Multi Page Applications

 + Single Page Applications - Only ONE HTML Page, Content is (re)rendered on Client - Typically only ONE ReactDOM.render() call

 + Multi Page Applications - Multi HTML Pages, Content is rendered on Server - One ReactDOM.render() call per "widget"

* Refreshing Next Generation Javascript
  :PROPERTIES:
  :CATEGORY: Next Generation Javascript
  :END:

** "let" and "const"

+ var - creates a variable in javascript

+ let - variable values
+ const - constant values


** Arrow Functions

#+BEGIN_QUOTE
Arrow functions are a different way of creating functions in JavaScript. Besides a shorter syntax, they offer advantages when it comes to keeping the scope of the this  keyword
#+END_QUOTE

#+BEGIN_QUOTE
Normal Javascript Function Syntax
#+END_QUOTE

#+BEGIN_SRC javascript
    function myFnc(arg) {
        console.log(arg);
    }
#+END_SRC

#+BEGIN_QUOTE
Arrow Function Syntax
#+END_QUOTE

#+BEGIN_SRC  javascript

    // if there is just one argument the parenthesis can be omitted, but if there is none or multiple arguments they must be present

    const myFnc = (arg) {
        console.log(arg);
    }
#+END_SRC


** Exports & Imports (Modules)

#+BEGIN_QUOTE
person.js
#+END_QUOTE

#+BEGIN_SRC  javascript
    const person = {
    name: 'Max'
    }

exports default person
#+END_SRC


#+BEGIN_QUOTE
utility.js
#+END_QUOTE

#+BEGIN_SRC  javascript
    export const clean = () => {...}
    export const baseData = 10;
#+END_SRC


#+BEGIN_QUOTE
app.js
#+END_QUOTE

#+BEGIN_SRC  javascript
// default export
import person from './person.js'
import prs from './person.js'

// named export
import { baseData } from '.utility.js'
import { clean as cln } from './utility.js' // using an alias
import * from './utility' // importing all using an alias from module
#+END_SRC


** Classes

#+BEGIN_SRC  javascript
// class declaration
class Human {

    let gender;

    constructor() {
        this.gender = 'male';
    }

    printGender() {
        console.log(this.gender);
    }

}

// Inheritance
class Person extends Human {

    let name;

    constructor() {
        super();
        this.name = 'user';
    }

    printUserName() {
    console.log(this.name)
    }
}

// class usage
const somePerson = new Person()

somePerson.printUserName();
somePerson.printGender();
#+END_SRC

** Classes, Properties and Methods

- Properties are like "variables attached to classes/objects"

#+BEGIN_SRC javascript
// ES6
constructor() {
this.property = "value";
}

//ES7
this.property = "value";
#+END_SRC


- Methods are like "functions attached to classes/objects"

#+BEGIN_SRC javascript
// ES6
someMethod () { ... }

//ES7
someMethod = () => { ... }
#+END_SRC


#+BEGIN_SRC javascript
// class declaration
class Human {

    let gender = 'male'

    printGender = () => {
        console.log(this.gender);
    }

}

// Inheritance
class Person extends Human {

    name = "user"
    gender = "female"

    printUserName() {
    console.log(this.name)
    }
}

// class usage
const somePerson = new Person()

somePerson.printUserName();
somePerson.printGender();

#+END_SRC


** Spread and Rest Operator

- Spread - Used to split up array elements or object properties

#+BEGIN_SRC javascript
const newArray = [...oldArray, 1, 2];

const newObject =  { ...oldObject, newProp: 5 };
#+END_SRC

#+BEGIN_SRC javascript
const numbers = [1, 2, 3];
const newNumbers = [...numbers, 4]
#+END_SRC

- Rest - Used to merge a list of function arguments into an array
#+BEGIN_SRC javascript
function sortArgs(args) {
    return args.sort()
}
#+END_SRC

#+BEGIN_SRC javascript
const person = {
name: 'Doe'
};

const newPerson =0 {
...person,
age: 20
};
#+END_SRC

** Destructuring

#+BEGIN_QUOTE
Easily extract array elements or object properties and store them in variables
#+END_QUOTE

#+BEGIN_SRC javascript
// Array Destructuring
[a, b] = ['Hello', 'Max']
#+END_SRC

#+BEGIN_SRC javascript
{name} = {name: 'Doe', age: 20}
#+END_SRC


* Understanding the Base Features & Syntax
  :PROPERTIES:
  :CATEGORY: Base Features & Syntax
  :END:

** Using a Build Workflow

*Why?*
 + Recommended for SPAs and MPAs
 + Optimize Code
 + Use Next-Gen JavaScript Features
 + Be more Productive

*How?*
 + Use Dependency Management Tool (npm or yarn)
 + use Bundler (recommended: Webpack)
 + Use Compiler (Next-Gen JavaScript) Babel + presets
 + Use a Development Server


* Working with Lists and Conditionals
  :PROPERTIES:
  :CATEGORY: Lists & Conditionals
  :END:

** JSX

** Components

Components are the core building block of React apps. Actually, React really is just a library for creating components in its core.
A typical React app therefore could be depicted as a component tree - having one root component ("App") and then an potentially infinite amount of nested child components.
Each component needs to return/ render some JSX code - it defines which HTML code React should render to the real DOM in the end.

+ Functional Components (also referred to as "presentational", "dumb" or "stateless" components - more about this later in the course) => const cmp = () => { return <div>some JSX</div> } (using ES6 arrow functions as shown here is recommended but optional)

+ Class Components (also referred to as "containers", "smart" or "stateful" components) => class Cmp extends Component { render () { return <div>some JSX</div> } }

** Props and State
props  and state  are CORE concepts of React. Actually, only changes in props  and/ or state  trigger React to re-render your components and potentially update the DOM in the browser (a detailed look at how React checks whether to really touch the real DOM is provided in section 6).

*Props*

props  allow you to pass data from a parent (wrapping) component to a child (embedded) component.

*Example:*

*AllPosts Component:*

#+BEGIN_SRC javascript
const posts = () => {
    return (
        <div>
            <Post title="My first Post" />
        </div>
    );
}
#+END_SRC

Here, title  is the custom property (prop ) set up on the custom Post  component. We basically replicate the default HTML attribute behavior we already know (e.g. <input type="text">  informs the browser about how to handle that input).

*Post Component:*

#+BEGIN_SRC javascript
const post = (props) => {
    return (
        <div>
            <h1>{props.title}</h1>
        </div>
    );
}
#+END_SRC

The Post  component receives the props  argument. You can of course name this argument whatever you want - it's your function definition, React doesn't care! But React will pass one argument to your component function => An object, which contains all properties you set up on <Post ... /> .

{props.title}  then dynamically outputs the title  property of the props  object - which is available since we set the title  property inside AllPosts  component (see above).


*State*

Whilst props allow you to pass data down the component tree (and hence trigger an UI update), state is used to change the component, well, state from within.
Changes to state also trigger an UI update.

*Example:*

*NewPost Component:*

#+BEGIN_SRC javascript
class NewPost extends Component { // state can only be accessed in class-based components!
    state = {
        counter: 1
    };

    render () { // Needs to be implemented in class-based components! Needs to return some JSX!
        return (
            <div>{this.state.counter}</div>
        );
    }
}
#+END_SRC

Here, the NewPost  component contains state . Only class-based components can define and use state . You can of course pass the state  down to functional components, but these then can't directly edit it.

state  simply is a property of the component class, you have to call it state  though - the name is not optional. You can then access it via this.state  in your class JSX code (which you return in the required render()  method).

Whenever state  changes (taught over the next lectures), the component will re-render and reflect the new state. The difference to props  is, that this happens within one and the same component - you don't receive new data (props ) from outside!


** Class, Pure and Function Components

React components come in different flavors to tackle different problems. In typical programming fashion, choosing which one works best gets an “it depends.” Each component type has its pros and cons depending on the problem at hand. The main takeaway is knowing how each component type is useful for a given scenario.

*** Class components (formerly ‘Stateful’ components)
The one component type we see all over the place is the class component. It is a stateful component because it has both state and props. This component has a ton of flexibility which is the reason why it is all over the place. A plus here is this has all component lifecycle methods in their raw form. This helps in tailoring the component to fit specific use cases. For example, firing an Ajax request right after the component mounts. One con is managing state manually with setState because of complexity and risk increase.

Type definition for class components looks like this:
#+BEGIN_SRC javascript
interface Component<P = {}, S = {}, SS = any> extends ComponentLifecycle<P, S, SS> { }
#+END_SRC


The ComponentLifecycle type definition has:
#+BEGIN_SRC javascript
interface ComponentLifecycle<P, S, SS = any> extends NewLifecycle<P, S, SS>, DeprecatedLifecycle<P, S> {
  componentDidMount?(): void;
  shouldComponentUpdate?(nextProps: Readonly<P>, nextState: Readonly<S>, nextContext: any): boolean;
  componentWillUnmount?(): void;
  componentDidCatch?(error: Error, errorInfo: ErrorInfo): void;
}
#+END_SRC

The following lifecycle methods are of interest:
+ *componentDidMount*: runs right after a component is mounted, setting state here triggers re-rendering
+ *shouldComponentUpdate*: determines whether changes in props and state warrants re-render, class components return true by default
+ *componentWillUnmount*: runs right before a component is destroyed, can do any necessary cleanup such as canceled network requests
+ *componentDidCatch*: catches exceptions from child components, unhandled exceptions unmount the component

With class components, we get all React has to offer. One check is to see if any lifecycle methods are necessary. If not, class components are too complex for the job at hand. Best to look at other ways to solve the problem by reducing complexity.

On the flip side, if complexity is a big concern, look into web hooks. Web hooks allow a functional paradigm while tapping into component state.

*** Pure components

Pure components have this type definition:
#+BEGIN_SRC javascript
class PureComponent<P = {}, S = {}, SS = any> extends Component<P, S, SS> { }
#+END_SRC

This means pure components support everything class components have plus more. For example, a pure component does a shallow comparison in shouldComponentUpdate by default. This optimization comes for free with pure components without any code. Unlike class components that return true by default, pure components optimize re-renders. One gotcha is to check that props and state are not complex nested objects. Also, avoid large props and state objects as this will affect React’s performance.

A shallow comparison goes one-level deep in props and state, for example:
#+BEGIN_SRC javascript
{
  "item": "strict value comparison",
  "nestedObject": {
    "item": "reference comparison"
  },
  "nestedArray": ["reference comparison"]
}
#+END_SRC

For this object, item gets a strict comparison of its value. But, nestedItem and nestedArray only get reference comparisons, or where it lives in memory. A shallow comparison stays at the top level to remain performant. It does not drill into nested objects or arrays because it is not a value comparison. One gotcha is shallow comparison might skip updates when only nested properties change. This can hide bugs that are difficult to track.

Consider using pure components for one-level deep state and props. Here, we get a bit of a boost by not re-rendering when state mutates. These components can live in tree leaf nodes which have simple data shapes.

For example:
#+BEGIN_SRC javascript
class LeafItem extends React.PureComponent {
  render() {
    return (<>
      {this.props.name} {this.props.description}
    </>);
  }
}
#+END_SRC

*** Function components (formerly ‘Stateless’ components)

A function component in React is defined like this:
#+BEGIN_SRC javascript
interface FunctionComponent<P = {}> {
  (props: PropsWithChildren<P>, context?: any): ReactElement | null;
  propTypes?: WeakValidationMap<P>;
  contextTypes?: ValidationMap<any>;
  defaultProps?: Partial<P>;
  displayName?: string;
}
#+END_SRC

This component type does not have any lifecycle methods. At a minimum, it must define a JavaScript function that returns ReactElement or null. All other properties such as propTypes and displayName are optional. A function component does not take in state and does not have setState. State mutation may happen in a parent component or a state machine like Redux. Function components re-render when state mutates and does not allow optimizations. This is not a deal-breaker because React performs reconciliation. Library internals figure out an optimal way to reconcile the virtual DOM with the one in the browser. This reconciliation process takes care of most performance concerns in React.

If performance is a big concern because reconciliation is not enough, take a look at React.memo. This is much like React.PureComponents but for function components vs classes.

Abstracting state mutation through Redux allows function components to focus on presentation. This makes it easy to test function components in a shallow renderer like Enzyme. A shallow renderer can check all test conditions by setting props. Reducers in Redux are pure functions that are also testable. This is because pure functions have a one-to-one mapping between input and output. A plus is all UI “logic” gets abstracted away from the presentation layer. This reduces cognitive load and aids dev creativity. Function components solve for most use cases in a neat clean way.

In simple terms, this is a function component:
#+BEGIN_SRC javascript
const LeafItem = ({name, description}) => <>{name} {description}</>;
 #+END_SRC



* Styling React Components & Elements
  :PROPERTIES:
  :CATEGORY: Styling React Components & Elements
  :END:

* Debugging React Apps
  :PROPERTIES:
  :CATEGORY: Debugging React Apps
  :END:

** Understanding Error Messages


** Using Dev Tools & Sourcemaps to find Logical Errors


** Using React Developer Tools


** Using Error Boundaries

* Diving Deeper into Components & React internals
  :PROPERTIES:
  :CATEGORY: Components & React Internals
  :END:

* Project Modules & Services

** Modules used:
+ create-react-app
+ radium
+ styled-components

* Useful Resources & Links
 :PROPERTIES:
  :CATEGORY: Useful Resources & Links
  :END:

+ [[https://github.com/facebookincubator/create-react-app][create-react-app]]

+ [[https://reactjs.org/docs/introducing-jsx.html][Introducing JSX]]

+ [[https://reactjs.org/docs/rendering-elements.html][Rendering Elements]]

+ [[https://reactjs.org/docs/components-and-props.html][Components & Props]]

+ [[https://blog.jscrambler.com/stateful-vs-stateless-vs-pure-react-components/][stateful-vs-stateless-vs-pure-react-components]]

+ [[https://reactjs.org/docs/events.html][Listenable Events]]

+ [[https://reactjs.org/docs/faq-state.html#gatsby-focus-wrapper][State and Props]]

+ [[https://lucybain.com/blog/2016/react-state-vs-pros/][ReactJs: Props vs. State]]

+ [[https://reactjs.org/docs/conditional-rendering.html][Conditional Rendering]]

+ [[https://reactjs.org/docs/lists-and-keys.html][Lists & Keys]]

+ [[https://medium.com/nulogy/how-to-use-css-modules-with-create-react-app-9e44bec2b5c2][Using CSS Modules in create-react-app Projects]]

+ [[https://github.com/css-modules/css-modules][More information about CSS Modules]]

+ [[https://reactjs.org/docs/error-boundaries.html][Error Boundaries]]

+ [[https://developers.google.com/web/tools/chrome-devtools/javascript/][Chrome Devtool Debugging]]
