#+TITLE:     React - The Complete Guide
#+AUTHOR:    Martim Lima
#+EMAIL:     (concat "martim.d.lima" at-sign "protonmail.com")
#+DATE:      10-10-2020
#+LANGUAGE:  en
#+OPTIONS:   H:4 num:nil toc:2
#+PROPERTY: header-args :dir ~/Documents/org/temp
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

-----

* Introduction
 :PROPERTIES:
  :CATEGORY: Introduction
  :END:

** What is React?

"A javascript Library for building User Interfaces"

A browser side javascript framework - no need for server side rendering

user Interfaces - Components - enable flexibility and reusibility by constructing small modular pieces of code

** Why React?
    :PROPERTIES:
    :CATEGORY: Introduction
    :END:

+ UI State becomes difficult to handle with Vanilla Javascript
+ Focus on Business Logic, not on preventing your App from exploding
+ Huge Ecosystem, Active Community, High Performance

** Single Page Applications / Multi Page Applications

 + Single Page Applications - Only ONE HTML Page, Content is (re)rendered on Client - Typically only ONE ReactDOM.render() call

 + Multi Page Applications - Multi HTML Pages, Content is rendered on Server - One ReactDOM.render() call per "widget"

* Refreshing Next Generation Javascript
  :PROPERTIES:
  :CATEGORY: Next Generation Javascript
  :END:

** "let" and "const"

+ var - creates a variable in javascript

+ let - variable values
+ const - constant values


** Arrow Functions

#+BEGIN_QUOTE
Arrow functions are a different way of creating functions in JavaScript. Besides a shorter syntax, they offer advantages when it comes to keeping the scope of the this  keyword
#+END_QUOTE

#+BEGIN_QUOTE
Normal Javascript Function Syntax
#+END_QUOTE

#+BEGIN_SRC javascript
    function myFnc(arg) {
        console.log(arg);
    }
#+END_SRC

#+BEGIN_QUOTE
Arrow Function Syntax
#+END_QUOTE

#+BEGIN_SRC  javascript

    // if there is just one argument the parenthesis can be omitted, but if there is none or multiple arguments they must be present

    const myFnc = (arg) {
        console.log(arg);
    }
#+END_SRC


** Exports & Imports (Modules)

#+BEGIN_QUOTE
person.js
#+END_QUOTE

#+BEGIN_SRC  javascript
    const person = {
    name: 'Max'
    }

exports default person
#+END_SRC


#+BEGIN_QUOTE
utility.js
#+END_QUOTE

#+BEGIN_SRC  javascript
    export const clean = () => {...}
    export const baseData = 10;
#+END_SRC


#+BEGIN_QUOTE
app.js
#+END_QUOTE

#+BEGIN_SRC  javascript
// default export
import person from './person.js'
import prs from './person.js'

// named export
import { baseData } from '.utility.js'
import { clean as cln } from './utility.js' // using an alias
import * from './utility' // importing all using an alias from module
#+END_SRC


** Classes

#+BEGIN_SRC  javascript
// class declaration
class Human {

    let gender;

    constructor() {
        this.gender = 'male';
    }

    printGender() {
        console.log(this.gender);
    }

}

// Inheritance
class Person extends Human {

    let name;

    constructor() {
        super();
        this.name = 'user';
    }

    printUserName() {
    console.log(this.name)
    }
}

// class usage
const somePerson = new Person()

somePerson.printUserName();
somePerson.printGender();
#+END_SRC

** Classes, Properties and Methods

- Properties are like "variables attached to classes/objects"

#+BEGIN_SRC javascript
// ES6
constructor() {
this.property = "value";
}

//ES7
this.property = "value";
#+END_SRC


- Methods are like "functions attached to classes/objects"

#+BEGIN_SRC javascript
// ES6
someMethod () { ... }

//ES7
someMethod = () => { ... }
#+END_SRC


#+BEGIN_SRC javascript
// class declaration
class Human {

    let gender = 'male'

    printGender = () => {
        console.log(this.gender);
    }

}

// Inheritance
class Person extends Human {

    name = "user"
    gender = "female"

    printUserName() {
    console.log(this.name)
    }
}

// class usage
const somePerson = new Person()

somePerson.printUserName();
somePerson.printGender();

#+END_SRC


** Spread and Rest Operator

- Spread - Used to split up array elements or object properties

#+BEGIN_SRC javascript
const newArray = [...oldArray, 1, 2];

const newObject =  { ...oldObject, newProp: 5 };
#+END_SRC

#+BEGIN_SRC javascript
const numbers = [1, 2, 3];
const newNumbers = [...numbers, 4]
#+END_SRC

- Rest - Used to merge a list of function arguments into an array
#+BEGIN_SRC javascript
function sortArgs(args) {
    return args.sort()
}
#+END_SRC

#+BEGIN_SRC javascript
const person = {
name: 'Doe'
};

const newPerson =0 {
...person,
age: 20
};
#+END_SRC

** Destructuring

#+BEGIN_QUOTE
Easily extract array elements or object properties and store them in variables
#+END_QUOTE

#+BEGIN_SRC javascript
// Array Destructuring
[a, b] = ['Hello', 'Max']
#+END_SRC

#+BEGIN_SRC javascript
{name} = {name: 'Doe', age: 20}
#+END_SRC


* Understanding the Base Features & Syntax
  :PROPERTIES:
  :CATEGORY: Base Features & Syntax
  :END:

** Using a Build Workflow

*Why?*
 + Recommended for SPAs and MPAs
 + Optimize Code
 + Use Next-Gen JavaScript Features
 + Be more Productive

*How?*
 + Use Dependency Management Tool (npm or yarn)
 + use Bundler (recommended: Webpack)
 + Use Compoler (Next-Gen JavaScript) Babel + presets
 + Use a Development Server


* Working with Lists and Conditionals
  :PROPERTIES:
  :CATEGORY: Lists & Conditionals
  :END:

** JSX

** Components

Components are the core building block of React apps. Actually, React really is just a library for creating components in its core.
A typical React app therefore could be depicted as a component tree - having one root component ("App") and then an potentially infinite amount of nested child components.
Each component needs to return/ render some JSX code - it defines which HTML code React should render to the real DOM in the end.

+ Functional Components (also referred to as "presentational", "dumb" or "stateless" components - more about this later in the course) => const cmp = () => { return <div>some JSX</div> } (using ES6 arrow functions as shown here is recommended but optional)

+ Class Components (also referred to as "containers", "smart" or "stateful" components) => class Cmp extends Component { render () { return <div>some JSX</div> } }

** Props and State
props  and state  are CORE concepts of React. Actually, only changes in props  and/ or state  trigger React to re-render your components and potentially update the DOM in the browser (a detailed look at how React checks whether to really touch the real DOM is provided in section 6).

*Props*

props  allow you to pass data from a parent (wrapping) component to a child (embedded) component.

*Example:*

*AllPosts Component:*

#+BEGIN_SRC javascript
const posts = () => {
    return (
        <div>
            <Post title="My first Post" />
        </div>
    );
}
#+END_SRC

Here, title  is the custom property (prop ) set up on the custom Post  component. We basically replicate the default HTML attribute behavior we already know (e.g. <input type="text">  informs the browser about how to handle that input).

*Post Component:*

#+BEGIN_SRC javascript
const post = (props) => {
    return (
        <div>
            <h1>{props.title}</h1>
        </div>
    );
}
#+END_SRC

The Post  component receives the props  argument. You can of course name this argument whatever you want - it's your function definition, React doesn't care! But React will pass one argument to your component function => An object, which contains all properties you set up on <Post ... /> .

{props.title}  then dynamically outputs the title  property of the props  object - which is available since we set the title  property inside AllPosts  component (see above).


*State*

Whilst props allow you to pass data down the component tree (and hence trigger an UI update), state is used to change the component, well, state from within.
Changes to state also trigger an UI update.

*Example:*

*NewPost Component:*

#+BEGIN_SRC javascript
class NewPost extends Component { // state can only be accessed in class-based components!
    state = {
        counter: 1
    };

    render () { // Needs to be implemented in class-based components! Needs to return some JSX!
        return (
            <div>{this.state.counter}</div>
        );
    }
}
#+END_SRC

Here, the NewPost  component contains state . Only class-based components can define and use state . You can of course pass the state  down to functional components, but these then can't directly edit it.

state  simply is a property of the component class, you have to call it state  though - the name is not optional. You can then access it via this.state  in your class JSX code (which you return in the required render()  method).

Whenever state  changes (taught over the next lectures), the component will re-render and reflect the new state. The difference to props  is, that this happens within one and the same component - you don't receive new data (props ) from outside!

* Styling React Components & Elements
  :PROPERTIES:
  :CATEGORY: Styling React Components & Elements
  :END:

* Debugging React Apps
  :PROPERTIES:
  :CATEGORY: Debugging React Apps
  :END:

* Diving Deeper into Components & React internals
  :PROPERTIES:
  :CATEGORY: Components & React Internals
  :END:


* Useful Resources & Links
 :PROPERTIES:
  :CATEGORY: Useful Resources & Links
  :END:

+ [[https://reactjs.org/docs/faq-state.html#gatsby-focus-wrapper][State and Props]]

+ [[https://lucybain.com/blog/2016/react-state-vs-pros/][ReactJs: Props vs. State]]







#+BEGIN_QUOTE

#+END_QUOTE

#+BEGIN_SRC javascript

#+END_SRC
